services:
  postgres:
    image: postgres:16-alpine
    container_name: educacion-asistencia-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: yura
      POSTGRES_PASSWORD: yura
      POSTGRES_DB: educacion_asistencia
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
